// This file is a placeholder for the generated env.rs file
// This file is automatically generated by build.rs
// Changes are ignored by version control

#![allow(dead_code)]

pub const APP_VERSION: &str = "0.0.0";
pub const APP_CONTRACT_ADDRESS: &str = "0x0000";
pub const APP_CHAIN_ID: &str = "0";
pub const APP_IPFS_GATEWAY_URL: &str = "http://localhost:8080";
