// This file is automatically generated by build.rs

#![allow(dead_code)]

pub const APP_VERSION: &str = "0.1.0";
pub const APP_NAME: &str = "krondor.Org";
pub const APP_CONTRACT_ADDRESS: &str = "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f";
pub const APP_CHAIN_ID: &str = "31337";
pub const APP_RPC_URL: &str = "http://localhost:8545";
pub const APP_IPFS_GATEWAY_URL: &str = "http://localhost:8080";
