// This file is automatically generated by build.rs

#![allow(dead_code)]

pub const APP_VERSION: &str = "2.0.0";
pub const APP_NAME: &str = "Krondor.Org";
pub const APP_CONTRACT_ADDRESS: &str = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
pub const APP_CHAIN_ID: &str = "31337";
pub const APP_RPC_URL: &str = "http://localhost:8545";
pub const APP_IPFS_GATEWAY_URL: &str = "http://localhost:8080";
